#!/bin/bash

rm build.xml
rm -r ~/src/reyna/reyna-test/junit

set -e
echo 'building reyna'
cd ~/src/reyna/reyna

android update project -p .
ant clean release

echo 'running lint'
cd ~/src/reyna
lint -Werror --ignore UnusedResources --exitcode .

echo 'running tests'
cd ~/src/reyna/reyna-test

ant test

echo "Tests OK"
