#!/bin/bash
set -e

echo 'building reyna'
cd ~/src/reyna/reyna
rm build.xml

android update project -p .
ant clean
ant release

echo 'running lint'
cd ~/src/reyna
lint -Werror .

echo 'running tests'
cd ~/src/reyna/reyna-test
ant "reyna-test (1)"
